name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/flutter-build-apk:latest 
        docker login docker.pkg.github.com --username $TOKEN
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/flutter-build-apk:latest
        docker login --username $DOCKER_USERNAME
        docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/flutter-build-apk:latest  $DOCKER_USERNAME/flutter-build-apk:latest
        docker push $DOCKER_USERNAME/flutter-build-apk:latest
      env:
        TOKEN: ${{ secrets.TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}